services:
  app:
    container_name: api-productos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      DB_HOST: 172.31.16.52
      DB_PORT: 8004        
      DB_NAME: bd_productos
      DB_USERNAME: root
      DB_PASSWORD: 72942250
    networks:
      - internal_network


networks:
  internal_network:
    external: true